# Generated by Django 4.2.7 on 2023-11-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumnos',
            new_name='Profesor',
        ),
        migrations.RenameField(
            model_name='carrera',
            old_name='carrera',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='curso',
            new_name='nombre',
        ),
    ]
